services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - embeddings

  embeddings:
    build: ./embeddings
    ports:
      - "8000:8000"

  frontend:
    build: ./client
    ports:
      - "80:80"
    environment:
      BACKEND_HOST: backend
    depends_on:
      - backend
