services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      HUGGINGFACE_API_KEY: ${HUGGINGFACE_API_KEY}

    dns:
      - 8.8.8.8
      - 8.8.4.4

  frontend:
    build: ./client
    ports:
      - "80:80"
    environment:
      BACKEND_HOST: backend
    depends_on:
      - backend
