services:
  db:
    build:
      context: ./docker
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: proteinviewer
    ports:
      - "5432:5432"

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/proteinviewer
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - db

  frontend:
    build: ./client
    ports:
      - "80:80"
    environment:
      BACKEND_HOST: backend
    depends_on:
      - backend
